packages:
  - apps/*
  - packages/*

catalog:
  # React ecosystem
  react: ^19.2.1
  react-dom: ^19.2.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3

  # TypeScript
  typescript: 5.9.2
  '@types/node': ^20.19.25

  # UI Libraries
  lucide-react: ^0.539.0
  next-themes: ^0.4.6

  # Validation
  zod: ^4.1.13

  # Sanity
  '@sanity/client': ^7.13.1

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
