packages:
  - apps/*
  - packages/*

catalog:
  # React ecosystem
  react: ^19.1.1
  react-dom: ^19.1.1
  "@types/react": ^19.1.10
  "@types/react-dom": ^19.1.7

  # TypeScript
  typescript: 5.9.2
  "@types/node": ^20.19.9

  # UI Libraries
  lucide-react: ^0.539.0
  next-themes: ^0.4.6

  # Validation
  zod: ^4.1.12

  # Sanity
  "@sanity/client": ^7.12.0

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
